spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/javatechie}
spring.datasource.username = ${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password = ${MYSQL_ROOT_PASSWORD:Password}
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
server.port=9191
